package newbank.server;

public enum Command {
	SHOWMYACCOUNTS, 
	NEWACCOUNT, 
	MOVE, 
	PAY, 
	SHOWCUSTOMERDETAIL, 
	
	UPDATECUSTOMERDETAIL,
	UPDATECUSTOMEREMAIL,
	UPDATECUSTOMERADDRESS,
	UPDATECUSTOMERDOB,
	UPDATECUSTOMERNAME,
	UPDATEUSERNAME,
	
	GETCUSTOMERNAME,
	GETCUSTOMEREMAIL,
	GETCUSTOMERADDRESS,
	GETCUSTOMERDOB,
	
	QUIT,
	LOGIN, 
	NEW_USER_REGISTRATION
}
